# ────────────────────────────────────────────────────────────
# Omarchy Felix Theme for Alacritty
# By Ty Richards
# https://github.com/TyRichards
# ────────────────────────────────────────────────────────────

[window]
# window padding {px}
padding.x = 20
padding.y = 20
decorations = "none"

[font]
size = 12.0


[colors]

[colors.normal]
black = "#333333"
red = "#D35F5F"
green = "#FFC107"
yellow = "#b91c1c"
blue = "#e68e0d"
magenta = "#D35F5F"
cyan = "#bebebe"
white = "#bebebe"

[colors.bright]
black = "#8a8a8d"
red = "#B91C1C"
green = "#FFC107"
yellow = "#b90a0a"
blue = "#f59e0b"
magenta = "#B91C1C"
cyan = "#eaeaea"
white = "#ffffff"

[colors.cursor]
cursor = '#c3b7b8'
text = '#2c2525'

[colors.primary]
background = '#000000'
foreground = '#e6d9db'
dim_foreground = "#8a8a8d"

[colors.selection]
background = '#403e41'
text = '#e6d9db'

[colors.vi_mode_cursor]
text = "#121212"
cursor = "#eaeaea"
# [colors.bright]
# black = "#000000"
# red = "#e7e9ea"
# green = "#e7e9ea"
# yellow = "#e7e9ea"
# blue = "#e7e9ea"
# magenta = "#e7e9ea"
# cyan = "#e7e9ea"
# white = "#e7e9ea"
